piaro:
  auto-start: true
  server-ip: "mc.ordaproject.net"
  global-vk-link: "https://vk.com/orda"
  footer-cta: "Заходи на сервер и зови друзей!"
  max-length: 700
  vk-api-version: "5.199"

  campaign-minutes-min: 60
  campaign-minutes-max: 120

  target-delay-min-minutes: 10
  target-delay-max-minutes: 20

  manual-approval: true
  max-targets-per-campaign: 20
  cooldown-minutes: 5

vk-profile:
  login: ""
  password: ""
  app-id: ""
  app-secret: ""
