name: OrdaVK
version: 1.0.0
main: ordacraft.vk.OrdaVKPlugin
api-version: '1.20'
author: OrdaCraft
commands:
  helpop:
    usage: /helpop <вопрос>
  ac:
    usage: /ac <вопрос>
  report:
    usage: /report <игрок> <причина>
  rep:
    usage: /rep <игрок> <причина>
  ordavk:
    usage: /ordavk <reload|bootstrap>
permissions:
  ordavk.reload:
    default: op
