name: OrdaVK Manager
version: 1.0.0
main: ordacraft.vk.OrdaVKPlugin
api-version: '1.20'
author: OrdaCraft
commands:
  helpop:
    usage: /helpop <question>
  report:
    usage: /report <player> <reason>
  ordavk:
    usage: /ordavk <reload|bootstrap>
permissions:
  ordavk.reload:
    default: op
