name: OrdaVK
version: 2.0Pro
main: ordacraft.vk.OrdaVKPlugin
api-version: '1.20'
author: OrdaCraft
commands:
  helpop:
    usage: /helpop <вопрос>
  ac:
    usage: /ac <вопрос>
  report:
    usage: /report <игрок> <причина>
  rep:
    usage: /rep <игрок> <причина>
  ordavk:
    usage: /ordavk <reload|bootstrap|status|doctor|testvk>
  ovk:
    usage: /ovk online
permissions:
  ordavk.reload:
    default: op
